# Generated by Django 2.0.1 on 2018-01-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('nickname', models.CharField(max_length=30, verbose_name='nickname')),
                ('school', models.CharField(max_length=50, null=True, verbose_name='school')),
                ('qq', models.CharField(max_length=20, verbose_name='qq')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
