# Generated by Django 2.0.1 on 2018-01-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qq',
        ),
        migrations.AddField(
            model_name='user',
            name='QQ',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ'),
        ),
    ]
