# Generated by Django 2.0.1 on 2018-01-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20180119_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acceptedNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='submitedNumber',
            field=models.IntegerField(default=0),
        ),
    ]
