# Generated by Django 2.0.1 on 2018-01-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_auto_20180127_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='acceptedNumber',
            field=models.IntegerField(default=0, verbose_name='acceptedNumber'),
        ),
        migrations.AlterField(
            model_name='user',
            name='submitedNumber',
            field=models.IntegerField(default=0, verbose_name='submitedNumber'),
        ),
    ]
