# Generated by Django 2.0.1 on 2018-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20180127_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acceptedNumber',
            new_name='overallSolved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='submitedNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='overallAttempted',
            field=models.IntegerField(default=0, verbose_name='overallAttempted'),
        ),
    ]
