# Generated by Django 2.0.1 on 2018-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_auto_20180127_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='overallSolved',
            field=models.IntegerField(default=0, verbose_name='overallSolved'),
        ),
    ]
