# Generated by Django 2.0.1 on 2018-01-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_auto_20180127_0703'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
