# Generated by Django 2.0.1 on 2018-01-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_auto_20180127_0738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
