# Generated by Django 2.0.2 on 2018-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_auto_20180131_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.IntegerField(default=0, verbose_name='is_superuser'),
        ),
    ]
