# Generated by Django 2.0.2 on 2018-02-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_auto_20180204_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
