# Generated by Django 2.0.1 on 2018-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='originalOJ',
            field=models.CharField(max_length=10, verbose_name='originalOJ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='originalProblem',
            field=models.CharField(max_length=20, verbose_name='originalProblem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problemUrl',
            field=models.CharField(max_length=255, verbose_name='problemUrl'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(max_length=100, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sourceUrl',
            field=models.CharField(max_length=255, null=True, verbose_name='sourceUrl'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updateTime',
            field=models.DateTimeField(verbose_name='updateTime'),
        ),
        migrations.AlterModelTable(
            name='problem',
            table='Problem',
        ),
    ]
