# Generated by Django 2.0.1 on 2018-01-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0002_auto_20180127_0740'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problem',
            table='problem',
        ),
    ]
