# Generated by Django 2.0.1 on 2018-01-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0003_auto_20180127_0745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problem',
            table='Problem',
        ),
    ]
