# Generated by Django 2.0.2 on 2018-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problem', '0004_auto_20180129_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='overallAccepted',
            field=models.IntegerField(default=0, verbose_name='overallAccepted'),
        ),
        migrations.AddField(
            model_name='problem',
            name='overallAttempted',
            field=models.IntegerField(default=0, verbose_name='overallAttempted'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='updateTime'),
        ),
    ]
